### ISSUE TITLE
UI 이펙트 및 애니메이션 추가

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#10]
1. UI 애니메이션
_전체 UI가 사라지고, 생성 되는 UI 

2. UI 이펙트
_배팅 이펙트
_결과창 이펙트(코인): 우승 플레이어에게 동전 들어가는 이펙트
_결과창 이펙트(트로피): 윈 플레이어에게 +숫자 이펙트, 로즈 플레이어에게 -숫자 이펙트

**Comment by ClientChai** [comment]
매칭화면과 결과화면에서 코인 이펙트 뜨도록 했습니다. 결과화면에서는 승/패에 따라 승리한 쪽으로 이펙트가 뜨도록 했습니다.
