### ISSUE TITLE
경기장 자동 포커스

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#12]
1. 경기장 소팅
_플레이어가 선택 할 수 있는 가장 상위 경기장 자동 포커스
_참가비가 부족하면 가능한 경기장 자동 포커스

2. 참가비 부족
_참가비가 부족한 경기장은 참가비 금액이 붉은색으로 보여진다.

**Comment by ClientChai** [comment]
1. 경기장 소팅 과 2. 참가비 부족 관련 작업 완료해 커밋했습니다.
