### ISSUE TITLE
인게임 컨트롤 과녁, 화살, 파렛트 리뉴얼

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#13]
인게임 컨트롤 과녁, 화살, 파렛트 리뉴얼
_제작된 리소스 붙이기
_이펙트 부분에 대해서도 같이 체크

**Comment by juwell75** [comment]
새로운 디자인으로 가이드 및 조준 시스템 리뉴얼 하는 작업 시작하였습니다.

**Comment by juwell75** [comment]
리뉴얼 관련 구성 데이터 작업 완료 했습니다.

**Comment by juwell75** [comment]
가이드 및 조준, 뒤로 당겼을때 파레트 적용했습니다. 
공을 당길때 공에서 공으로 드래깅되는 느낌의 이팩트 적용에 문제가 생겨 미뤄지고 있습니다.

**Comment by ClientChai** [comment]
과녁, 화살, 파레트 리뉴얼 관련해 커밋했습니다. 25일 버전에서 있었던 장갑아이템 사용시 화살표 끝에 맺히는 파티클도 다시 부활시켰습니다. 공을 당겼을 때 당겨진 공에서 시작 위치의 반투명한 공으로 향하는 이펙트는 작업에 다소 시간이 걸릴듯 하여 우선순위를 뒤로 미루었습니다.
