### ISSUE TITLE
환경 텍스트

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#16]
플레이어의 플레이 상황에 따라 출력되는 텍스트

**Comment by juwell75** [comment]
디자인 및 Unity 프리팹 구성 완료 했습니다.

**Comment by ClientChai** [comment]
마지막 프레임의 후공인 플레이어의 턴일 때 선공인 플레이어와의 점수 차이에 따라 이기기 위한 조건을 띄우도록 작업해 커밋했습니다. 메시지는 공을 움직일 수 있는 상태(ready state)에 뜨고 노출시간은 3초이며 유저가 공을 당긴 상태가 되면 노출시간이 남아있어도 시야에 방해가 되지 않도록 사라지게 했습니다.
