### ISSUE TITLE
경기장 선택 버그

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#17]
경기장 선택시 일어나는 버그(433)
_경기장이 선택 UI가 작아진다.
_서로 겹쳐서 보인다

*궁극적으로는 스와이프 기능이 들어가야 한다.

**Comment by ClientChai** [comment]
좌/우 버튼 연타 시 경기장 UI가 작아지거나 가운데로 오지 않는 현상 있어 연타도 가능하도록 수정했습니다.
