### ISSUE TITLE
핀 리셋 타이밍

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#18]
핀 리셋 타이밍
_던지기 준비 화면에서 핀 리셋이 되면 안된다.
_공 던지고 결과 나올 때 해당 UI 뒤에서 리셋되어야 한다.
_던질 준비를 하고 있을 때 핀 리셋이 되면 플레이어는 오해를 하게 된다.

**Comment by ClientChai** [comment]
작업 완료했습니다. 내일 한번 확인 부탁드립니다.

**Comment by zipi-norion** [comment]
테스트 해본 결과 리셋 시스템이 없는 것으로 보이는데.. 다시 한번 확인 부탁 드립니다.

![스크린샷 2019-10-25 오전 10 57 20](https://user-images.githubusercontent.com/56715890/67537502-a587ea80-f716-11e9-91e5-6ae7ebb82a0c.png)
![스크린샷 2019-10-25 오전 10 57 26](https://user-images.githubusercontent.com/56715890/67537503-a6208100-f716-11e9-9a04-9f336a7012db.png)

**Comment by zipi-norion** [comment]
멀티모드에서는 작동하고 연습모드에서 작동하지 않는 것으로 최종 확인 했습니다.
수고 많으셨습니다.

**Comment by ClientChai** [comment]
핀과 카메라의 리셋 타이밍 다시 조절해서 커밋했습니다.
