### ISSUE TITLE
나이스 투구에 대한 이펙트

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#19]
플레이어가 무엇인가 잘? 던졌다 라는 느낌을 주기 위한 방안
1. 기존 투구 결과(굿, 나이스, 그레이트)중 나이스, 그레이트 판정을 받을 때 볼링공에 반짝이는 이펙트를 추가
2. 플레이어로 하여금 내가 무엇인가 잘? 던졌나? 정도 감정을 느끼게 해주는 방향

기타 다른 의견이 있으시면 말씀 부탁 드립니다.

**Comment by juwell75** [comment]
디자인 완료, 데이터 작성 완료, 
파티클은 배팀장님한테 의뢰 했습니다. 
구성은 클라이언트에서 구성해야 합니다.

**Comment by ClientChai** [comment]
순간적으로 이펙트를 팡 터트리는 작업은 완료해 커밋했습니다. 짧은 시간동안 공의 꽁무니에서 출력되는 이펙트는 아직 작업을 못했습니다.
