### ISSUE TITLE
스코어 보드 점수 방식 수정

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#20]
기존 스코어 보드 점수 방식을 볼링킹 방식으로 수정

기존 스코어 보드
_현재 프레임 점수
_최대치 예상 점수(max)

수정 스코어 보드
_현재 플레임 점수(기존과 동일)
_지금 투구한 것 까지의 점수(total)

달라진 점
_전 맥스 스코어 자리에 토탈 스코어가 들어간다.
_토탈 스코어는 다음 투구에 플레이어가 0개를 던진다는 가정을 하고 현재 점수롤 표시 해주는 것이다.
_예) 1프레임: 1프레임 첫 투구 9개, 스페어 1개/2프레임 첫 번째 투구 스트라이크
_예) 현재 토탈 점수: 30점(정상적인 계산이라면 20점만 표기 되어야 한다. 이유는 2프레임 스트라이크 점수가 3프레임 투구 결과 합산이 되어야 하기 때문이다)
_[https://www.youtube.com/watch?v=XSgchnvt9Hw]

**Comment by mjmj-norion** [comment]
수정되었습니다.

**Comment by ClientChai** [comment]
작업 완료되었습니다.
