### ISSUE TITLE
라이벌 턴 일때 인지 문제

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#21]
상대방이 플레이를 할 때 인지가 쉽지 않다.
인지를 쉽게 하기 위한 방법이 필요 하다.
제안)
라이벌턴 텍스트 출력 위치 이동
_라이벌턴 텍스트를 상단으로 올린다.
_라이벌턴 텍스트는 알파애니메이션을 한다. (희미하게 보였다가 잘 보였다가..)

스포츠게임 카메라
_스포츠 게임 카메라 처럼 구성을 바꿔 본다.

등등

의견 부탁 드립니다.

**Comment by mjmj-norion** [comment]
참고: 볼링킹은 라이벌턴시에 카메라가 약간 사이드에서 비춥니다.

**Comment by zipi-norion** [comment]
ㅎㅎ 처음 부터 볼링킹 방식으로 했으면 편하긴 했을 텐데.. 골프 클래시 방식을 선택해서 고생 하내요.

**Comment by juwell75** [comment]
일단 디자인에서 커다랗게 빨간 바탕에 카메라 아이콘이 그려진 형태로 구성하였습니다. 
상대의 컨트롤과 점수, 판정등을 보는데 영향이 최소화되는 위치로 현재 볼링스킨 교체 버튼 자리에 
rival - turn 표시가 나오도록 구성하였습니다. 
이렇게 해서 프로그램 적용 후 상태를 보고 추가 구성을 하도록 하겠습니다.
