### ISSUE TITLE
볼링공 속도/회전에 따른 사운드 이펙트

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#24]
볼링공 속도/회전에 따른 사운드 이펙트

_속도가 빠를 때 사운드 이펙트
_회전이 많을 때 사운드 이펙트

**Comment by ClientChai** [comment]
공을 당긴 정도(0 ~ 0.33, 0.33 ~ 0.66, 0.66 ~ 1)에 따라 공의 롤/거터/쿠션 사운드를 slow/mid/fast 로 출력하고 핀 사운드는 slow/mid/fast에 추가로 몇개의 핀들이 상호 충돌했는지에 따라 각각 level1 ~ level5 사운드가 출력되도록 했습니다.
공의 slow/mid/fast 기준이 되는 당김값은 scriptable_object의 01.game 맨 밑에 Standard Speed_Slow/Middle로 조절하실 수 있습니다.
핀의 충돌정보를 모으는 시간은 Time Gather Collision Info로 조절하실 수 있으며 현재는 공의 속도가 slow일때는 0.3초, fast일때는 0.2초 동안 정보를 수집하도록 해놨습니다.
핀 충돌 사운드의 level을 증가시키는데 필요한 충돌 개수는 Collision Count for Increase Level로 설정하며, 현재는 slow에서는 2, fast는 5로 해놨습니다.

ex> 공을 당긴 정도가 0.7이면 공이 굴러가는 사운드는 fast사운드 출력, fast상태에서 최초의 충돌이 발생한 후 0.2초 동안 수집한 공과 핀, 핀과 핀의 충돌 개수가 총 16개라면 collision Count For Increase level이 5일때 핀 충돌사운드는 Fast_Level4가 출력되고 충돌 개수가 총 20개 이상이면 Fast_Level5가 출력.
