### ISSUE TITLE
게임 로고 인트로 화면

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#26]
인트로 화면
_게임 로고 나오기
_로딩 프로그래스 또는  업데이트 프로그래스

현재 인트로 화면 이후 메인메뉴 화면에서 로드하고 있는 상황
이 부분 수정 및 인트로 화면에 로딩 프로그래스 리소스 투입

**Comment by zipi-norion** [comment]
이 부분도 체크 부탁 드립니다.

**Comment by juwell75** [comment]
현재는 Ci - 타이틀 - 매인 진입 형태로 전부 분리가 되었습니다. 
타이틀에서 로딩 프로세스를 진행 하는 형태입니다. 
로딩화면을 구성할 때 같이 로딩 바 디자인을 해서 적용할 예정입니다.

**Comment by ClientChai** [comment]
타이틀 화면에서 서버 테이블과 로비 씬 로딩 상황이 반영되도록 프로그래스바를 제작했습니다. 또한 타이틀화면에서 네트워크 연결이 확인된 시점에 즉각 비동기로 로비씬을 로딩하기 시작함으로서 타이틀에서 로비로 넘어가는 시간을 단축시켰습니다.
