### ISSUE TITLE
433 인트로 화면

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#27]
433에 인트로 화면에 사용할 수 있는 리소스 요청 중(사운드 리소스 포함)
리소스 받은 후 적용

**Comment by juwell75** [comment]
그래픽 이미지 및 애니메이션 적용 완료 했습니다.

**Comment by zipi-norion** [comment]
433에 사운드 리소스 문의 했습니다. 전달되면 공유 드리겠습니다.
