### ISSUE TITLE
테스트 환경 조성 요청

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#29]
1. 직선 투구 테스트
_투구시 직선(회전X)으로 'Great' 판정이 무조건 나올 수 있게
_직선 투구시 볼링공 파운드에 따른 핀 판결 변화 체크를 위해

2. 볼링핀 무게
_볼링핀에 무게 개념을 넣어서 테스트 할 수 있게
_볼링핀 무게에 따라 핀 액션이 어떻게 달라지는지 확인
_볼링핀 각각에 무게 입력이 될 수 있게

**Comment by zipi-norion** [comment]
직선 투구 대비 훅 투구 스트라이크 확률을 2:8 정도로 생각하고 있습니다.

**Comment by ClientChai** [comment]
볼링핀 각각의 무게를 조절해서 테스트 할 수 있도록 하여 커밋했습니다.

**Comment by ClientChai** [comment]
공을 직선으로 보내는 기능도 커밋했습니다. train모드에서 화면 좌측의 공 버튼을 클릭하시면 직선 투구 기능을 on/off 할 수 있습니다.
