### ISSUE TITLE
UI 화면 별 Anchor 재설정

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#3]
UI 해상도에 따른 앵커 설정

**Comment by juwell75** [comment]
1차 완료 

추후 작업 시 카메라 스페이스로 변경 할 경우 
좌표 및 스케일 틀어지는 부분이 발생 할 수 있습니다. 

이팩트 추가 작업시 확인 및 수정 합니다.

**Comment by juwell75** [comment]
현재 상황에서 완료 되었습니다.
