### ISSUE TITLE
스코어 계산 방식 변경

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#32]
기존 스코어 계산 방식을 커렌트 플레임 방식으로 변경 합니다.

스트라이크: 30점
스페어:10점 + 첫 투구 점수
예)9핀/스페어=10점 + 9점(첫 투구 점수)
오픈(스페어 처리를 하지 못한 상황): 핀 개수만 점수로 인정(기존과 동일)

마지막 프레임: 보너스 투구샷 없음(즉, 기존 최대 3번 던질 수 있는 것이 2번으로 변경)

**Comment by juwell75** [comment]
디자인 쪽 수정해서 프리팹 적용했습니다.
