### ISSUE TITLE
강하게 던질 때 시뮬레이션 가이드 문제

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#33]
강하게 던질 때 설정한 가이드 방향대로 공이 가지를 못 함

**Comment by ClientChai** [comment]
가이드라인으로 인한 프레임 저하를 잡기 위해 특정 조건을 충족했을때만 가이드라인을 갱신하도록 하는 과정에서 발생되었던 문제로 현재는 로직을 수정해 다시 커밋했습니다.
