### ISSUE TITLE
인게임 아이템 사용 이펙트 및 가이드 라인 이펙트

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#4]
인게임 아이템 사용 이펙트
_가이드 라인 길어지는 이펙트
_화살표 느려지는 이펙트

가이드 라인 이펙트
_모든 레인에서 잘 보일 수 있도록 하는 이펙트

**Comment by zipi-norion** [comment]
담당자 추가 했습니다.

**Comment by ClientChai** [comment]
가이드라인 잘 보이도록 하는 작업 완료했습니다. 장갑 아이템 사용 이펙트는 방향 화살표에 파티클을 달았고 신발 아이템 이펙트는 일단 아이템 적용 시 가이드라인 내부의 화살표들이 전체적으로 분홍빛을 띠도록 했습니다.

**Comment by zipi-norion** [comment]
수고 많으셨습니다.
다음 주에 이 부분들에 디테일 작업 잘 부탁 드립니다.

**Comment by juwell75** [comment]
새로운 디자인으로 가이드 및 조준 시스템 리뉴얼 하는 작업 시작하였습니다.
