### ISSUE TITLE
결과창 코인 및 트로피 속도

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#5]
결과창 코인 및 트로피 속도 빠르게
가감에 대한 속도가 너무 느림 지금 보다 빠르게

**Comment by ClientChai** [comment]
코인과 트로피 각각의 카운트 시간을 다르게 설정할 수 있도록 작업했고 현재는 코인은 5초에서 3초, 트로피는 5초에서 1초로 줄여놨습니다.

**Comment by zipi-norion** [comment]
결과창 부분 테스트 할 때 보여주시면 감사 하겠습니다.
