### ISSUE TITLE
연습 아이콘, 친구와 하기 아이콘

### ISSUE THREAD

**Issue by zipi-norion** [norionsoft/no16#8]
연습하기 아이콘
_아이콘 디자인 추가

친구와 아이콘
_보이지 않게(임시)

**Comment by juwell75** [comment]
완료

친구와 게임 하기 버튼 - 현재 노출이 않되게끔 꺼놓은 상태입니다. 

연습 모드 진입 버튼은 따로 제작하여 붙여놓았고 작동 상태입니다.
